export const ErrorCodes = {
  // Auth
  AUTH_MISSING_SESSION:       'AUTH_MISSING_SESSION',
  AUTH_EXPIRED_SESSION:       'AUTH_EXPIRED_SESSION',
  AUTH_INVALID_TOKEN:         'AUTH_INVALID_TOKEN',
  AUTH_MAGIC_LINK_EXPIRED:    'AUTH_MAGIC_LINK_EXPIRED',
  AUTH_TURNSTILE_FAILED:      'AUTH_TURNSTILE_FAILED',

  // RBAC
  RBAC_FORBIDDEN:             'RBAC_FORBIDDEN',
  RBAC_ADMIN_ONLY:            'RBAC_ADMIN_ONLY',

  // Validation
  VALIDATION_FAILED:          'VALIDATION_FAILED',
  VALIDATION_DOMAIN_INVALID:  'VALIDATION_DOMAIN_INVALID',

  // Projects
  PROJECT_NOT_FOUND:          'PROJECT_NOT_FOUND',
  PROJECT_DOMAIN_EXISTS:      'PROJECT_DOMAIN_EXISTS',
  PROJECT_REQUIRED:           'PROJECT_REQUIRED',

  // Agents
  AGENT_NOT_FOUND:            'AGENT_NOT_FOUND',
  AGENT_INACTIVE:             'AGENT_INACTIVE',
  AGENT_CONFIG_NOT_FOUND:     'AGENT_CONFIG_NOT_FOUND',
  AGENT_INPUT_SCHEMA_INVALID: 'AGENT_INPUT_SCHEMA_INVALID',

  // Execution
  EXECUTION_NOT_FOUND:        'EXECUTION_NOT_FOUND',
  EXECUTION_AI_ERROR:         'EXECUTION_AI_ERROR',
  EXECUTION_PROMPT_INJECTION: 'EXECUTION_PROMPT_INJECTION',

  // Vectorize
  VECTOR_LIMIT_EXCEEDED:      'VECTOR_LIMIT_EXCEEDED',
  VECTOR_SEARCH_ERROR:        'VECTOR_SEARCH_ERROR',

  // Rate Limit
  RATE_LIMIT_EXCEEDED:        'RATE_LIMIT_EXCEEDED',

  // Customer
  CUSTOMER_NOT_FOUND:         'CUSTOMER_NOT_FOUND',

  // Generic
  INTERNAL_ERROR:             'INTERNAL_ERROR',
  NOT_FOUND:                  'NOT_FOUND',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
